#!/bin/bash

# Vercel Build Script for GitHub Actions Auto-Generated Assets
# This script is used when Flutter Web assets are auto-generated by GitHub Actions
# and committed to the repository

set -e
trap 'echo "ERROR: Build failed at line $LINENO"; exit 1' ERR

echo "=========================================="
echo "=== Vercel Build (GitHub Actions) ==="
echo "=========================================="
echo "Working directory: $(pwd)"
echo "Timestamp: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
echo ""

# STEP 1: Verify project structure
echo "[STEP 1] Verifying project structure..."

if [ ! -d "epl_match_simulator" ]; then
  echo "ERROR: epl_match_simulator directory not found"
  exit 1
fi

if [ ! -d "api" ] || [ ! -f "api/predictMatch.js" ]; then
  echo "ERROR: api/predictMatch.js not found"
  exit 1
fi

echo "✓ Project structure verified"
echo ""

# STEP 2: Check for pre-built assets (generated by GitHub Actions)
echo "[STEP 2] Checking for Flutter Web assets..."

if [ ! -d "epl_match_simulator/build/web" ]; then
  echo "⚠ Pre-built assets not found"
  echo "Note: GitHub Actions should auto-generate them on push"
  echo "Commit hash: $(git rev-parse HEAD 2>/dev/null || echo 'unknown')"
  echo ""
  echo "If this is the first deployment:"
  echo "  1. Push to branch to trigger GitHub Actions"
  echo "  2. Wait for workflow to complete"
  echo "  3. Retry deployment"
  exit 1
fi

# Verify critical files
CRITICAL_FILES=("epl_match_simulator/build/web/index.html" \
                "epl_match_simulator/build/web/main.dart.js" \
                "epl_match_simulator/build/web/flutter.js")

for file in "${CRITICAL_FILES[@]}"; do
  if [ ! -f "$file" ]; then
    echo "ERROR: Critical file missing: $file"
    exit 1
  fi
done

echo "✓ Flutter Web assets verified"
echo "  - Files: $(find epl_match_simulator/build/web -type f | wc -l)"
echo "  - Size: $(du -sh epl_match_simulator/build/web | cut -f1)"
echo ""

# STEP 3: Verify API layer
echo "[STEP 3] Verifying Serverless Functions..."

if [ ! -f "api/predictMatch.js" ]; then
  echo "ERROR: api/predictMatch.js not found"
  exit 1
fi

echo "✓ API function verified"
echo "  - File: api/predictMatch.js"
echo ""

# STEP 4: Final status
echo "[STEP 4] Final verification..."
echo "✓ Frontend: READY"
echo "✓ API: READY"
echo ""

echo "=========================================="
echo "=== Build Complete ==="
echo "=========================================="
echo ""
echo "Deployment ready:"
echo "  - Frontend: epl_match_simulator/build/web/"
echo "  - API: api/predictMatch.js"
echo "  - Status: All checks passed"
echo ""
